# Generated by Django 3.2.4 on 2021-06-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado_em', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('lido', models.BooleanField(verbose_name='Lido')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('resenha', models.CharField(max_length=255, verbose_name='Resenha')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
